[package]
name = "makods"
authors = ["mako yass"]
version = "0.2.0"
description = "Provides the jostle tree, A data structure for working with long sequences of variable-width spans"
repository = "https://github.com/makoConstruct/jostletree.rs"
license = "MIT"

[dev-dependencies]
rand = "0.3.0"